<!--<script src="/mapas/js/jquery.js"></script>    -->
<link rel="stylesheet" type="text/css" href="/mapas/css/verticalmenu.css" media="screen">
       <script type="text/javascript">
	   var menum = jQuery.noConflict();
        menum(document).ready(function () {
           menum('#nav li a').click(function(){
                var s = menum(this).attr('id');
                var imgid=menum("#"+s+" img").attr('id');
                var imgsrc=menum("#"+imgid+"").attr('src');
                if(imgsrc=="/mapas/images/insert.jpg")
                {
                    menum("#"+imgid+"").attr('src','/mapas/images/remove.jpg');
                    menum(this).next().slideDown(800);
                }
                else
                {
                    menum("#"+imgid+"").attr('src','/mapas/images/insert.jpg');
                    menum(this).next().slideUp(800);
                }
            });
           menum("#menu li a").mouseover(function() {
               var s = menum(this).attr('id');
                var imgid=menum("#"+s+" img").attr('id');
                var imgsrc=menum("#"+imgid+"").attr('src');
                if(imgsrc=="/mapas/images/insert.jpg")
                {
                    menum("#"+imgid+"").attr('src','/mapas/images/remove.jpg');
                    menum(this).parent().find(".count").slideDown('medium').show(); 
                }
		menum(this).parent().hover(function() 
		{
		}, 
		function()
		{	menum("#"+imgid+"").attr('src','/mapas/images/insert.jpg');
			menum(this).parent().find(".count").slideUp('slow'); 
		});
                
            });
            menum('#onclick').attr('checked', true);
            menum('#onclick').click(function(){
                menum("#click").show();
                menum("#onover").hide();
                menum('#mouseover').attr('checked', false);
            });
            menum('#mouseover').click(function(){
                 menum("#click").hide();
                menum("#onover").show();
                menum('#onclick').attr('checked', false);
            });
        });
        </script>
<div class="col-md-2" style="padding: 0px;" style="padding:0px;">
 <div  id='onover' style='display: block;'>
    <div class="left"> 
    <ul id="menu">
        <li>
		    <a id='im6' ><img src="/mapas/images/insert.jpg" id="4" align='left'>Acuaticos</a>
			 <ul class='count'>
				<li><a ><input type='checkbox' style=" margin: 0px 5px 0px 0px;" id='c_0' class='c_0' onclick='jsMuestraOculta("c_0","centroAcuatico","0")' >	Centro acuatico</a></li>
				<li><a ><input type='checkbox' style=" margin: 0px 5px 0px 0px;" id='c_1' class='c_1' onclick='jsMuestraOculta("c_1","atletismo","1")'>Atletismo</a></li>
				<li><a ><input type='checkbox' style=" margin: 0px 5px 0px 0px;" id='c_2' class='c_2' onclick='jsMuestraOculta("c_2","bownling","2")'>Bownling</a></li>
			 </ul>
        </li>
        <li><a id='im7' ><img src="/mapas/images/insert.jpg" id="5" align='left'>Ciclismo</a>
            <ul class='count'>
<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_3' class='c_3' onclick='jsMuestraOculta("c_3","bmx","3")'>BMX</a></li>
<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_4' class='c_4' onclick='jsMuestraOculta("c_4","mtb","4")'>MTB</a></li>
<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_22' class='c_22' onclick='jsMuestraOculta("c_22","pista","22")'>Pista</a></li>
            </ul>
        </li>
<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_5' class='c_5' onclick='jsMuestraOculta("c_5","lucha","5")'>Lucha</a></li>
<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_6' class='c_6' onclick='jsMuestraOculta("c_6","gimnacia","6")'>Gimnacia</a></li>
          
        </li>
        <li><a id='im8' ><img src="/mapas/images/insert.jpg" id="6" align='left'>Patidronomo</a>
            <ul class='count'>
             
                <li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_7' class='c_7' onclick='jsMuestraOculta("c_7",patinajeCarrera","7")'>Carrera</a></li>
                <li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_8' class='c_8' onclick='jsMuestraOculta("c_8",patinajeArtistico","8")'>Artisitico</a></li>
            </ul>
        </li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_9'  class='c_9'  onclick='jsMuestraOculta( "c_9","fronton","9")'>Pelota Fronton</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_10' class='c_10' onclick='jsMuestraOculta("c_10","raquetbol","10")'>Raquetbol</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_11' class='c_11' onclick='jsMuestraOculta("c_11","squash","11")'>Squash</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_12' class='c_12' onclick='jsMuestraOculta("c_12","tiroarco","12")'>Tiro Con Arco</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_13' class='c_13' onclick='jsMuestraOculta("c_13","voleibolPlaya","13")'>Voleibol Playa</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_14' class='c_14' onclick='jsMuestraOculta("c_14","karate","14")'>Karate</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_15' class='c_15' onclick='jsMuestraOculta("c_15","taekwondo","15")'>Taekwondo</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_16' class='c_16' onclick='jsMuestraOculta("c_16","baloncesto","16")'>Baloncesto</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_17' class='c_17' onclick='jsMuestraOculta("c_17","balonmano","17")'>Balon Mano</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_18' class='c_18' onclick='jsMuestraOculta("c_18","rugby","18")'>Rugby</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_19' class='c_19' onclick='jsMuestraOculta("c_19","box","19")'>Boxeo</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_20' class='c_20' onclick='jsMuestraOculta("c_20","triatlon","20")'>Triatlon</a></li>
		<li><a id='im8' ><input type='checkbox' id='c_21' class='c_21' onclick='jsMuestraOculta("c_21","nauticos","21")'><img src="/mapas/images/insert.jpg" id="6" align='left'>Nauticos</a>
            <ul class='count'>
               <li><a >Canotaje</a></li>
                <li><a >Esqui Nautico</a></li>
				<li><a >Aguas Abiertas</a></li>
				<li><a >Remo</a></li>
				<li><a >Vela</a></li>
            </ul>
        </li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_23' class='c_23' onclick='jsMuestraOculta("c_23","futbol","23")'>Futbol</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_24' class='c_24' onclick='jsMuestraOculta("c_24","pesas","24")'>Hockey Cesped</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_25' class='c_25' onclick='jsMuestraOculta("c_25","pesas","25")'>Levantamiento De Pesas</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_26' class='c_26' onclick='jsMuestraOculta("c_26","tenisMesa","26")'>Tenis De Mesa</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_27' class='c_27' onclick='jsMuestraOculta("c_27","voleibol","27")'>Voleibol</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_28' class='c_28' onclick='jsMuestraOculta("c_28","ecuestre","28")'>Ecuestre</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_29' class='c_29' onclick='jsMuestraOculta("c_29","tiro","29")'>Tiro</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_30' class='c_30' onclick='jsMuestraOculta("c_30","futsal","30")'>Futsal</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_31' class='c_31' onclick='jsMuestraOculta("c_31","tenis","31")'>Tenis</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_32' class='c_32' onclick='jsMuestraOculta("c_32","golf","32")'>Golf</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_33' class='c_33' onclick='jsMuestraOculta("c_33","esgrima","33")'>Esgrima</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_34' class='c_34' onclick='jsMuestraOculta("c_34","badminton","34")'>Badminton</a></li>
		<li><a ><input type='checkbox'  style=" margin: 0px 5px 0px 0px;"id='c_35' class='c_35' onclick='jsMuestraOculta("c_35","judo","35")'>Judo</a></li>
		
		</ul>
    </div>
    </div>  
</div>

<div class="col-md-10 img-rounded img-thumbnail" style="border: 2px solid #000; height: 600px;" id="mapa_trabajo">
    
</div>
<script type="text/javascript">
 //en esta lista guardaremos los markers para poder tener acceso desde cualquier funcion de javascript
 var lstMarkers= [];

//variable global que guardara el objeto mapa de google, es global para tener acceso a ella en cualquier funcion
var map;

//inicializamos el mapa ejecutando la funcion de abajo que crea los markers
inicializaMapa();

function inicializaMapa() {

            //posicion del mapa
			var posicionCentro = new google.maps.LatLng(-17.4194 , -66.1325);
			//posiciones de los markers
			var centroAcuatico    = new google.maps.LatLng(-17.40158, -66.17401);/*centro acuatico*/
			var atletismo = new google.maps.LatLng(-17.41033, -66.14797);/*atletismo*/
			var bownling          = new google.maps.LatLng(-17.35979, -66.16821);/*bowling*/
			var bmx               = new google.maps.LatLng(-17.38476, -66.20544);/*ciclismo BMX*/
			var mtb               = new google.maps.LatLng(-17.39208, -66.13525);/*ciclismo MTB*/
			var lucha             = new google.maps.LatLng(-17.39062, -66.16534);/*lucha*/
			var gimnacia          = new google.maps.LatLng(-17.40505, -66.18532);/*gimnacia*/
		    var patinajecarrera   = new google.maps.LatLng(-17.38483, -66.20735);/*patinaje carrera*/
			var patinajeartistico = new google.maps.LatLng(-17.35087, -66.1863);/*patinaje artistico*/
			var fronton 		  = new google.maps.LatLng(-17.38581, -66.20635);/*fronton*/
			var raquetbol 		  = new google.maps.LatLng(-17.36956, -66.17625);/*raquetbol*/
		    var squash 			  = new google.maps.LatLng(-17.40382, -66.17055);/*squash*/
			var tiroarco 		  = new google.maps.LatLng(-17.40568, -66.131);/*tiro con arco*/
			var voleibolplaya 	  = new google.maps.LatLng(-17.40765, -66.18018);/*voleibol de playa*/
			var karate 	          = new google.maps.LatLng(-17.3956, -66.24268);/*karate*/
		    var taekwondo 	      = new google.maps.LatLng(-17.33884, -66.21253);/*Taekwondo*/
			var baloncesto 	      = new google.maps.LatLng(-17.40814, -66.28917);/*baloncesto*/
			var balonmano 	      = new google.maps.LatLng(-17.39868, -66.02221);/*balonmano*/
			var rugby 	          = new google.maps.LatLng(-17.40697, -66.03919);/*rugby*/
			var box 	          = new google.maps.LatLng(-17.54295, -65.83655);/*box*/
			var triatlon 	      = new google.maps.LatLng(-17.22713, -65.89153);/*triatlon*/
		    var nauticos 	      = new google.maps.LatLng(-17.52945, -66.08515);/*nauticos*/
			var ciclismopista     = new google.maps.LatLng(-17.39934, -66.17348);/*ciclismo pista*/
			var futbol    		  = new google.maps.LatLng(-17.3793, -66.16176);/*futbol*/
			var hokeycesped    	  = new google.maps.LatLng(17.37953, -66.16351);/*hokeycesped*/
			var pesas    	  = new google.maps.LatLng(-17.3895, -66.16472);/*pesas*/
			var tenismesa    	  = new google.maps.LatLng(-17.38113, -66.16128);/*tenis de mesa*/
			var voleibol    	  = new google.maps.LatLng(-17.40115, -66.16105);/*voleibol*/
			var ecuestre    	  = new google.maps.LatLng(-17.60033, -66.03861);/*ecuestre - tiro*/
			var futsal    	  = new google.maps.LatLng(-17.00691, -65.44175);/*futsal*/
			var tenis    	  = new google.maps.LatLng(-16.95674, -65.39987);/*tenis*/
			var golf    	  = new google.maps.LatLng(-17.40485, -66.12904);/*golf*/
			var esgrima    	  = new google.maps.LatLng(-17.52569, -65.9659);/*esgrima*/
			var badminton    	  = new google.maps.LatLng(-17.58974, -65.93008);/*badminton*/
			var judo    	  = new google.maps.LatLng(-17.39133, -66.31467);/*judo*/
            //opciones de mapa
            var mapOptions = {   zoom: 13,     center: posicionCentro,   mapTypeId: google.maps.MapTypeId.ROADMAP  };

           //creamos el mapa en el div con el id "mapa"
            map = new google.maps.Map(document.getElementById('mapa_trabajo'),mapOptions);

		/* agregamos 2 iconos rojos y 2 iconos azules
		para ello crearemos 4 objetos de javascript que contendra el marker y aparte una bandera
		la cual dira que tipo es, si es tipo ROJO o tipo AZUL
		*/
		var TipoCentroAcuatico=new Object();var Tipoatletismo=new Object();	var TipoBowling=new Object();
		var TipoBmx=new Object();			var TipoMtb=new Object();				var TipoLucha=new Object();
		var TipoGimnacia=new Object();		var TipoPatinajeCarrera=new Object();	var TipoPatinajeArtistico=new Object();
		var TipoFronton=new Object();		var TipoRaquetbol=new Object();			var TipoScuash=new Object();
		var TipoTiroArco=new Object();		var TipoVoleiboPlaya=new Object();		var TipoKarate=new Object();
		var TipoTaekwondo=new Object();		var TipoBaloncesto=new Object();		var TipoBalonmano=new Object();
		var TipoRugby=new Object();	   	    var TipoBox=new Object();				var TipoTriatlon=new Object();
		var TipoNauticos=new Object();		var TipoCiclismoPista=new Object();		var TipoFutbol=new Object();
		var TipoHokeyCesped=new Object();	var TipoPesas=new Object();				var TipoTenisMesa=new Object();
		var TipoVoleibol=new Object();		var TipoEcuestre=new Object();			var TipoFutsal=new Object();
		var TipoTenis=new Object();			var TipoGolf=new Object();				var TipoEsgrima=new Object();
		var TipoBadminton=new Object();		var TipoJudo=new Object();
		
		//procedemos a crear el marker y asignarselos a los objetos junto a su tipo
		TipoCentroAcuatico.tipo="acuatico";
        TipoCentroAcuatico.marker = new google.maps.Marker({
            position: centroAcuatico,    map: map,	icon:"/images/punto_kantuta.png",
            title: 'Centro Acuatico'
        });
		Tipoatletismo.tipo="atletismo";
        Tipoatletismo.marker = new google.maps.Marker({
            position: atletismo,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Atletismo'
        });
		TipoBowling.tipo="bowling";
        TipoBowling.marker = new google.maps.Marker({
            position: bownling,   map: map,	icon:"/images/punto_kantuta.png",
            title: 'Bowling'
        });
		TipoBmx.tipo="bmx";
        TipoBmx.marker = new google.maps.Marker({
            position: bmx,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Ciclismo BMX'
        });
		TipoMtb.tipo="mtb";
        TipoMtb.marker = new google.maps.Marker({
            position: mtb,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Ciclismo MTB'
        });
		TipoLucha.tipo="lucha";
        TipoLucha.marker = new google.maps.Marker({
            position: lucha,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Lucha'
        });
		TipoGimnacia.tipo="gimnacia";
        TipoGimnacia.marker = new google.maps.Marker({
            position: gimnacia,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Gimnacia'
        });
		TipoPatinajeCarrera.tipo="patinajeCarrera";
        TipoPatinajeCarrera.marker = new google.maps.Marker({
            position: patinajecarrera,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Patinaje Carrera'
        });
		TipoPatinajeArtistico.tipo="patinajeArtistico";
        TipoPatinajeArtistico.marker = new google.maps.Marker({
            position: patinajeartistico,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Patinaje Artistico'
        });
		TipoFronton.tipo="fronton";
        TipoFronton.marker = new google.maps.Marker({
            position: fronton,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Fronton'
        });
		TipoRaquetbol.tipo="raquetbol";
        TipoRaquetbol.marker = new google.maps.Marker({
            position: raquetbol,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Raquetbol'
        });
		TipoScuash.tipo="squash";
        TipoScuash.marker = new google.maps.Marker({
            position: squash,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Squash'
        });
		TipoTiroArco.tipo="tiroArco";
        TipoTiroArco.marker = new google.maps.Marker({
            position: tiroarco,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Tiro Con Arco'
        });
		TipoVoleiboPlaya.tipo="voleibolPlaya";
        TipoVoleiboPlaya.marker = new google.maps.Marker({
            position: voleibolplaya,  map: map,	icon:"/images/punto_kantuta.png",
            title: 'Voleibol De Playa'
        });
		TipoKarate.tipo="karate";
        TipoKarate.marker = new google.maps.Marker({
            position: karate,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Karate'
        });
		TipoTaekwondo.tipo="taekwondo";
        TipoTaekwondo.marker = new google.maps.Marker({
            position: karate,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Taekwondo'
        });
		TipoBaloncesto.tipo="baloncesto";
        TipoBaloncesto.marker = new google.maps.Marker({
            position: baloncesto,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Baloncesto'
        });
		TipoBalonmano.tipo="balonmano";
        TipoBalonmano.marker = new google.maps.Marker({
            position: balonmano,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Balonmano'
        });
		TipoRugby.tipo="rugby";
        TipoRugby.marker = new google.maps.Marker({
            position: rugby,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Rugby'
        });
		TipoBox.tipo="box";
        TipoBox.marker = new google.maps.Marker({
            position: box,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Box'
        });
		TipoTriatlon.tipo="triatlon";
        TipoTriatlon.marker = new google.maps.Marker({
            position: triatlon,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Triatlon'
        });
		TipoNauticos.tipo="nauticos";
        TipoNauticos.marker = new google.maps.Marker({
            position: nauticos,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Nauticos'
        });
		TipoCiclismoPista.tipo="ciclismoPista";
        TipoCiclismoPista.marker = new google.maps.Marker({
            position: ciclismopista,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Ciclismo Pista'
        });
		TipoFutbol.tipo="Futbol";
        TipoFutbol.marker = new google.maps.Marker({
            position: futbol,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Futbol'
        });
		TipoHokeyCesped.tipo="hockeyCesped";
        TipoHokeyCesped.marker = new google.maps.Marker({
            position: hokeycesped,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Hockey Cesped'
        });
		TipoPesas.tipo="Levantamiento De Pesas";
        TipoPesas.marker = new google.maps.Marker({
            position: pesas,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Levantamiento De Pesas'
        });
		TipoTenisMesa.tipo="tenisMesa";
        TipoTenisMesa.marker = new google.maps.Marker({
            position: tenismesa,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Tenis De Mesa'
        });
		TipoVoleibol.tipo="voleibol";
        TipoVoleibol.marker = new google.maps.Marker({
            position: voleibol,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Voleibol'
        });
		TipoEcuestre.tipo="ecuestreTiro";
        TipoEcuestre.marker = new google.maps.Marker({
            position: ecuestre,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Ecuestre - Tiro'
        });
		TipoFutsal.tipo="futsal";
        TipoFutsal.marker = new google.maps.Marker({
            position: futsal,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Futsal'
        });
		TipoTenis.tipo="tenis";
        TipoTenis.marker = new google.maps.Marker({
            position: tenis,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Tenis'
        });
		TipoGolf.tipo="golf";
        TipoGolf.marker = new google.maps.Marker({
            position: golf,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Golf'
        });
		TipoEsgrima.tipo="esgrima";
        TipoEsgrima.marker = new google.maps.Marker({
            position: golf,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Esgrima'
        });
		TipoBadminton.tipo="badminton";
        TipoBadminton.marker = new google.maps.Marker({
            position: badminton,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Badminton'
        });
		TipoJudo.tipo="judo";
        TipoJudo.marker = new google.maps.Marker({
            position: judo,  map: map,icon:"/images/punto_kantuta.png",
            title: 'Judo'
        });
/**********************************************************************************/
		var infowindow = new google.maps.InfoWindow({  content: 'Bowling'	});
		  google.maps.event.addListener(TipoBowling.marker, 'click', function() {
		  infowindow.open(map,TipoBowling.marker);
		});
		var infowindow1 = new google.maps.InfoWindow({  content: 'Ciclismo BMX'	});
		  google.maps.event.addListener(TipoBmx.marker, 'click', function() {
		  infowindow1.open(map,TipoBmx.marker);
		});
		var infowindow2 = new google.maps.InfoWindow({  content: 'Atletismo'	});
		  google.maps.event.addListener(Tipoatletismo.marker, 'click', function() {
		  infowindow2.open(map,Tipoatletismo.marker);
		});
		var infowindow3 = new google.maps.InfoWindow({  content: 'Centro Acuatico'	});
		  google.maps.event.addListener(TipoCentroAcuatico.marker, 'click', function() {
		  infowindow3.open(map,TipoCentroAcuatico.marker);
		});
		var infowindow4 = new google.maps.InfoWindow({  content: 'Ciclismo MTB'	});
		  google.maps.event.addListener(TipoMtb.marker, 'click', function() {
		  infowindow4.open(map,TipoMtb.marker);
		});
		var infowindow5 = new google.maps.InfoWindow({  content: 'Lucha'	});
		  google.maps.event.addListener(TipoLucha.marker, 'click', function() {
		  infowindow5.open(map,TipoLucha.marker);
		});
		var infowindow6 = new google.maps.InfoWindow({  content: 'Gimnacia'	});
		  google.maps.event.addListener(TipoGimnacia.marker, 'click', function() {
		  infowindow6.open(map,TipoGimnacia.marker);
		});
		var infowindow7 = new google.maps.InfoWindow({  content: 'Patinaje Carrera'	});
		  google.maps.event.addListener(TipoPatinajeCarrera.marker, 'click', function() {
		  infowindow7.open(map,TipoPatinajeCarrera.marker);
		});
		var infowindow8 = new google.maps.InfoWindow({  content: 'Patinaje Artistico'	});
		  google.maps.event.addListener(TipoPatinajeArtistico.marker, 'click', function() {
		  infowindow8.open(map,TipoPatinajeArtistico.marker);
		});
		var infowindow9 = new google.maps.InfoWindow({  content: 'Fronton'	});
		  google.maps.event.addListener(TipoFronton.marker, 'click', function() {
		  infowindow9.open(map,TipoFronton.marker);
		});
		var infowindow10 = new google.maps.InfoWindow({  content: 'Raquetbol'	});
		  google.maps.event.addListener(TipoRaquetbol.marker, 'click', function() {
		  infowindow10.open(map,TipoRaquetbol.marker);
		});
		var infowindow11 = new google.maps.InfoWindow({  content: 'Squash'	});
		  google.maps.event.addListener(TipoScuash.marker, 'click', function() {
		  infowindow11.open(map,TipoScuash.marker);
		});
		var infowindow12 = new google.maps.InfoWindow({  content: 'Tiro Con Arco'	});
		  google.maps.event.addListener(TipoTiroArco.marker, 'click', function() {
		  infowindow12.open(map,TipoTiroArco.marker);
		});
		var infowindow13 = new google.maps.InfoWindow({  content: 'Voleibol De Playa'	});
		  google.maps.event.addListener(TipoVoleiboPlaya.marker, 'click', function() {
		  infowindow13.open(map,TipoVoleiboPlaya.marker);
		});
		var infowindow14 = new google.maps.InfoWindow({  content: 'Karate'	});
		  google.maps.event.addListener(TipoKarate.marker, 'click', function() {
		  infowindow14.open(map,TipoKarate.marker);
		});
		var infowindow15 = new google.maps.InfoWindow({  content: 'Taekwondo'	});
		  google.maps.event.addListener(TipoTaekwondo.marker, 'click', function() {
		  infowindow15.open(map,TipoTaekwondo.marker);
		});
		var infowindow16 = new google.maps.InfoWindow({  content: 'Baloncesto'	});
		  google.maps.event.addListener(TipoBaloncesto.marker, 'click', function() {
		  infowindow16.open(map,TipoBaloncesto.marker);
		});
		var infowindow17 = new google.maps.InfoWindow({  content: 'Balonmano'	});
		  google.maps.event.addListener(TipoBalonmano.marker, 'click', function() {
		  infowindow17.open(map,TipoBalonmano.marker);
		});
		var infowindow18 = new google.maps.InfoWindow({  content: 'Rugby'	});
		  google.maps.event.addListener(TipoRugby.marker, 'click', function() {
		  infowindow18.open(map,TipoRugby.marker);
		});
		var infowindow19 = new google.maps.InfoWindow({  content: 'Box'	});
		  google.maps.event.addListener(TipoBox.marker, 'click', function() {
		  infowindow19.open(map,TipoBox.marker);
		});
		var infowindow20 = new google.maps.InfoWindow({  content: 'Triatlon'	});
		  google.maps.event.addListener(TipoTriatlon.marker, 'click', function() {
		  infowindow20.open(map,TipoTriatlon.marker);
		});
		var infowindow21 = new google.maps.InfoWindow({  content: 'Nauticos'	});
		  google.maps.event.addListener(TipoNauticos.marker, 'click', function() {
		  infowindow21.open(map,TipoNauticos.marker);
		});
		var infowindow22 = new google.maps.InfoWindow({  content: 'Ciclismo Pista'	});
		  google.maps.event.addListener(TipoCiclismoPista.marker, 'click', function() {
		  infowindow22.open(map,TipoCiclismoPista.marker);
		});
		var infowindow23 = new google.maps.InfoWindow({  content: 'Futbol'	});
		  google.maps.event.addListener(TipoFutbol.marker, 'click', function() {
		  infowindow23.open(map,TipoFutbol.marker);
		});
		var infowindow24 = new google.maps.InfoWindow({  content: 'Hockey Cesped'	});
		  google.maps.event.addListener(TipoHokeyCesped.marker, 'click', function() {
		  infowindow24.open(map,TipoHokeyCesped.marker);
		});
		var infowindow25 = new google.maps.InfoWindow({  content: 'Levantamiento De Pesas'	});
		  google.maps.event.addListener(TipoPesas.marker, 'click', function() {
		  infowindow25.open(map,TipoPesas.marker);
		});
		var infowindow26 = new google.maps.InfoWindow({  content: 'Tenis De Mesa'	});
		  google.maps.event.addListener(TipoTenisMesa.marker, 'click', function() {
		  infowindow26.open(map,TipoTenisMesa.marker);
		});
		var infowindow27 = new google.maps.InfoWindow({  content: 'Voleibol'	});
		  google.maps.event.addListener(TipoVoleibol.marker, 'click', function() {
		  infowindow27.open(map,TipoVoleibol.marker);
		});
		var infowindow28 = new google.maps.InfoWindow({  content: 'Ecuestre<br/>Tiro'	});
		  google.maps.event.addListener(TipoEcuestre.marker, 'click', function() {
		  infowindow28.open(map,TipoEcuestre.marker);
		});
		var infowindow29 = new google.maps.InfoWindow({  content: 'Futsal'	});
		  google.maps.event.addListener(TipoFutsal.marker, 'click', function() {
		  infowindow29.open(map,TipoFutsal.marker);
		});
		var infowindow30 = new google.maps.InfoWindow({  content: 'Tenis'	});
		  google.maps.event.addListener(TipoTenis.marker, 'click', function() {
		  infowindow30.open(map,TipoTenis.marker);
		});
		var infowindow31 = new google.maps.InfoWindow({  content: 'Golf'	});
		  google.maps.event.addListener(TipoGolf.marker, 'click', function() {
		  infowindow31.open(map,TipoGolf.marker);
		});
		var infowindow32 = new google.maps.InfoWindow({  content: 'Esgrima'	});
		  google.maps.event.addListener(TipoEsgrima.marker, 'click', function() {
		  infowindow32.open(map,TipoEsgrima.marker);
		});
		var infowindow33 = new google.maps.InfoWindow({  content: 'Badminton'	});
		  google.maps.event.addListener(TipoBadminton.marker, 'click', function() {
		  infowindow33.open(map,TipoBadminton.marker);
		});
		var infowindow34 = new google.maps.InfoWindow({  content: 'Judo'	});
		  google.maps.event.addListener(TipoJudo.marker, 'click', function() {
		  infowindow34.open(map,TipoJudo.marker);
		});
/*********************bmx**********************/
	/*var popup = new google.maps.InfoWindow({content: 'Ciclismo BMX'});
popup.open(map, TipoBmx.marker);
var popup1 = new google.maps.InfoWindow({content: 'Bowling'});
popup1.open(map, TipoBowling.marker);
var popup2 = new google.maps.InfoWindow({content: 'Atletismo'});
popup2.open(map, Tipoatletismo.marker);
	var popup3 = new google.maps.InfoWindow({content: 'Centro Acuatico<br/>Natación Carrera<br/>Nado Sincronizado<br/>Clavado<br/>Polo Acuatico'});
popup3.open(map, TipoCentroAcuatico.marker);
	var popup4 = new google.maps.InfoWindow({content: 'Ciclismo MTB'});
popup4.open(map, TipoMtb.marker);
	var popup5 = new google.maps.InfoWindow({content: 'Lucha'});
popup5.open(map, TipoLucha.marker);
var popup6 = new google.maps.InfoWindow({content: 'Gimnacia<br/>Artistica<br/>Ritmica<br/>Trampolin'});
popup6.open(map, TipoGimnacia.marker);
var popup7 = new google.maps.InfoWindow({content: 'Patinaje Carrera'});
popup7.open(map, TipoPatinajeCarrera.marker);
var popup8 = new google.maps.InfoWindow({content: 'Patinaje Artistico'});
popup8.open(map, TipoPatinajeArtistico.marker);
var popup9 = new google.maps.InfoWindow({content: 'Fronton'});
popup9.open(map, TipoFronton.marker);
var popup10 = new google.maps.InfoWindow({content: 'Raquetbol'});
popup10.open(map, TipoRaquetbol.marker);
var popup11 = new google.maps.InfoWindow({content: 'Squash'});
popup11.open(map, TipoScuash.marker);
var popup12 = new google.maps.InfoWindow({content: 'Tiro Con Arco'});
popup12.open(map, TipoTiroArco.marker);
var popup13 = new google.maps.InfoWindow({content: 'Voleibol De Playa'});
popup13.open(map, TipoVoleiboPlaya.marker);
var popup14 = new google.maps.InfoWindow({content: 'Karate'});
popup14.open(map, TipoKarate.marker);
var popup15 = new google.maps.InfoWindow({content: 'Taekwondo'});
popup15.open(map, TipoTaekwondo.marker);
var popup16 = new google.maps.InfoWindow({content: 'Baloncesto'});
popup16.open(map, TipoBaloncesto.marker);
var popup17 = new google.maps.InfoWindow({content: 'Balonmano'});
popup17.open(map, TipoBalonmano.marker);
var popup18 = new google.maps.InfoWindow({content: 'Rugby'});
popup18.open(map, TipoRugby.marker);
var popup19 = new google.maps.InfoWindow({content: 'Box'});
popup19.open(map, TipoBox.marker);
var popup20 = new google.maps.InfoWindow({content: 'Box'});
popup20.open(map, TipoTriatlon.marker);
var popup21 = new google.maps.InfoWindow({content: 'Nauticos<br/>Canotaje<br/>Esqui Nautico<br/>Aguas Abiertas<br/>Remo<br/>Vela'});
popup21.open(map, TipoNauticos.marker);
var popup22 = new google.maps.InfoWindow({content: 'Ciclismo Pista'});
popup22.open(map, TipoCiclismoPista.marker);
var popup23 = new google.maps.InfoWindow({content: 'Futbol'});
popup23.open(map, TipoFutbol.marker);
var popup24 = new google.maps.InfoWindow({content: 'Hockey Cesped'});
popup24.open(map, TipoHokeyCesped.marker);
var popup25 = new google.maps.InfoWindow({content: 'Levantamiento De Pesas'});
popup25.open(map, TipoPesas.marker);
var popup26 = new google.maps.InfoWindow({content: 'Tenis De Mesa'});
popup26.open(map, TipoTenisMesa.marker);
var popup27 = new google.maps.InfoWindow({content: 'Voleibol'});
popup27.open(map, TipoVoleibol.marker);
var popup28 = new google.maps.InfoWindow({content: 'Ecuestre<br/> Adiestramiento<br/>Salto'});
popup28.open(map, TipoEcuestre.marker);
var popup29 = new google.maps.InfoWindow({content: 'Futsal'});
popup29.open(map, TipoFutsal.marker);
var popup30 = new google.maps.InfoWindow({content: 'Tenis'});
popup30.open(map, TipoTenis.marker);
var popup31 = new google.maps.InfoWindow({content: 'Golf'});
popup31.open(map, TipoGolf.marker);
var popup32 = new google.maps.InfoWindow({content: 'Esgrima'});
popup32.open(map, TipoEsgrima.marker);
var popup33 = new google.maps.InfoWindow({content: 'Badminton'});
popup33.open(map, TipoBadminton.marker);
var popup34 = new google.maps.InfoWindow({content: 'Judo'});
popup34.open(map, TipoJudo.marker);*/
/*************************************************************************************/
		//una vez creador los objetos junto con su marker y tipo los agregaremos a la lista global que creamos con anterioridad
		lstMarkers.push(TipoCentroAcuatico);lstMarkers.push(Tipoatletismo);	        lstMarkers.push(TipoBowling);
		lstMarkers.push(TipoBmx);			lstMarkers.push(TipoMtb);				lstMarkers.push(TipoLucha);
		lstMarkers.push(TipoGimnacia);		lstMarkers.push(TipoPatinajeCarrera);	lstMarkers.push(TipoPatinajeArtistico);
		lstMarkers.push(TipoFronton);		lstMarkers.push(TipoRaquetbol);			lstMarkers.push(TipoScuash);
		lstMarkers.push(TipoTiroArco);		lstMarkers.push(TipoVoleiboPlaya);		lstMarkers.push(TipoKarate);
		lstMarkers.push(TipoTaekwondo);		lstMarkers.push(TipoBaloncesto);		lstMarkers.push(TipoBalonmano);
		lstMarkers.push(TipoRugby);			lstMarkers.push(TipoBox);				lstMarkers.push(TipoTriatlon);
		lstMarkers.push(TipoNauticos);		lstMarkers.push(TipoCiclismoPista);		lstMarkers.push(TipoFutbol);
		lstMarkers.push(TipoHokeyCesped);	lstMarkers.push(TipoPesas);				lstMarkers.push(TipoTenisMesa);
		lstMarkers.push(TipoVoleibol);		lstMarkers.push(TipoEcuestre);			lstMarkers.push(TipoFutsal);
		lstMarkers.push(TipoTenis);			lstMarkers.push(TipoGolf);				lstMarkers.push(TipoEsgrima);
		lstMarkers.push(TipoBadminton);		lstMarkers.push(TipoJudo);
		
		//el metodo push sirve para agregar un elemento a una lista o arreglo en javascript
/******************cuando se haga click*******************/
		
    }

//función que realiza la operacion de evaluar los markers y si estos se ocultaran o mostraran dependiendo el checkbox presionado
function jsMuestraOculta(tipoIcono,nombre,ind){

	if(document.getElementById(tipoIcono).checked){var muestra=true;}else{var muestra=false;}
	if(muestra)
		lstMarkers[ind].marker.setMap(map);
			else
		lstMarkers[ind].marker.setMap(null);
}

</script>

