 <!--<div class="full_container">-->
 <style>
     .valws{
         font-size: 19px;
     }
 </style>
 <div class="cronometro_mascota col-md-12" style=" margin-bottom: 8px; ">
         <div id="callout-helper-context-color-specificity" class="bs-callout bs-callout-info" style="background: none; background-color:#f3d63a; ">
	    <h3>
                <?php echo $this->translate("Los juegos en número");?>
            </h3>
	</div>
     <p style="font-weight: bold;    font-size: 16px;">
         <?php //echo $this->translate("Faltan Para los juegos Suramericanos");?>
     </p>
      <section class="center_container main_image" style="position:relative;">
        <div class="count_container">
          
          <div class="countdown countdown-container " style=""><!--container-->
              <div class="clock row col-md-12" style="padding-left: 22px;height: 100px;margin: 0px auto;">
                  <div class="clock-item clock-days countdown-time-value  col-md-6" style="float: left;">
                    <div class="wrap">
                        <div class="inner">
                            <div id="canvas-days" class="clock-canvas" style="background:#d78d22"></div>

                            <div class="text">
                                <p class="valws">35</p>
                                <p class="type-days type-time" style="margin-top:24px; color:#337ab7;"> <?php echo $this->translate("Modalidades deportivas");?></p>
                            </div><!-- /.text -->
                        </div><!-- /.inner -->
                    </div><!-- /.wrap -->
                </div><!-- /.clock-item -->

                <div class="clock-item clock-hours countdown-time-value  col-md-6" style="float: left;">
                    <div class="wrap">
                        <div class="inner">
                            <div id="canvas-hours" class="clock-canvas"  style="background:#919d31"></div>

                            <div class="text">
                                <p class="valws">260</p>
                                <p class="type-hours type-time" style="margin-top:24px;color:#337ab7;"><?php echo $this->translate("Pruebas");?></p>
                            </div><!-- /.text -->
                        </div><!-- /.inner -->
                    </div><!-- /.wrap -->
                </div><!-- /.clock-item -->

                <div class="clock-item clock-minutes countdown-time-value  col-md-6" style="float: left;">
                    <div class="wrap">
                        <div class="inner">
                            <div id="canvas-minutes" class="clock-canvas"  style="background: #f3d634"></div>

                            <div class="text">
                                <p class="valws">40</p>
                                <p class="type-minutes type-time" style="margin-top:24px;color:#337ab7;"><?php echo $this->translate("Arenas");?></p>
                            </div><!-- /.text -->
                        </div><!-- /.inner -->
                    </div><!-- /.wrap -->
                </div><!-- /.clock-item -->

                <div class="clock-item clock-seconds countdown-time-value col-md-6" style="float: left;">
                    <div class="wrap">
                        <div class="inner">
                            <div id="canvas-seconds" class="clock-canvas"  style="background:#579ade"></div>

                            <div class="text">
                                <p class="valws">14</p>
                                <p class="type-seconds type-time" style="margin-top:24px;color:#337ab7;"><?php echo $this->translate("Paises");?></p>
                            </div><!-- /.text -->
                        </div><!-- /.inner -->
                    </div><!-- /.wrap -->
                </div><!-- /.clock-item -->
            </div><!-- /.clock -->
        </div><!-- /.countdown-wrapper -->

        </div>
      </section>
    <!--</div>-->
    </div>