 
  <style type="text/css">
div#wn { 
   height: 1071px;
    overflow: hidden;
    position: relative;
    width: 100%;
    float: left;
  
    }
</style>
<script src="/noticia/dw_con_scroller.js" type="text/javascript"></script>
<script type="text/javascript">

if ( DYN_WEB.Scroll_Div.isSupported() ) {
	
	DYN_WEB.Event.domReady( function() {
		// arguments: id of scroll area div, id of content div
		var wndo = new DYN_WEB.Scroll_Div('wn', 'lyr');
		// see info online at http://www.dyn-web.com/code/scrollers/continuous/documentation.php
		wndo.makeSmoothAuto( {axis:'v', bRepeat:true, repeatId:'rpt', speed:30, bPauseResume:true} );
		
	});
}

</script>
<div class="col-md-12" style=" padding: 0;    height: 420px;    float: left;    color: #222;    font-size: 16px;   overflow: hidden;">
        
    
<div class="scrollable vertical">
  <div class="items">
      <div id="wn">
    <div id="lyr">
      <?php if($this->principal){
          $dat=$this->principal; $jj=1;
          foreach ($dat as $d){    ?>
                <div class="caja_noticia">
                    <div class="col-md-12 caja_decripcion">
                        <p style="text-align: justify;color: #000; text-align: center;width: 100%;"><?php echo ucwords(strtolower($d["Nombre"]))." (". ucwords(strtolower($d["vol_titulo_".$this->idioma])).")";?></p> 
                    </div>

                </div>
        <?php } 
        
        foreach ($dat as $d){        ?>
         <div class="caja_noticia"  id="rpt">
                    
                    <div class="col-md-12 caja_decripcion">
                        <p style="text-align: justify; color: #fff; text-align: center;width: 100%;"><?php echo ucwords(strtolower($d["Nombre"]))." (". ucwords(strtolower($d["vol_titulo_".$this->idioma])).")";?></p> 
                    </div>

                </div>
        <?php }
          }else{     ?>
      <h3> <?php echo $this->translate("No se tiene informacion")?></h3>
      <?php }?>
          </div>
</div>
  </div>
</div>
  </div>
