<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
            
		<?php
		
		echo $this->headTitle();
		echo $this->headMeta();
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/default_bo.css')
                    ->prependStylesheet('/css/bootstrap/bootstrap.min.css') 
                         ->prependStylesheet('/css/hover.css')
                          ->prependStylesheet('/css/glm.css')
                        
                    ->prependStylesheet('/css/bootstrap/asstes/ie10-viewport-bug-workaround.css')
                        ;
		echo $this->headStyle();
		echo $this->headScript()
                ->appendFile('/js/bootstrap/jquery-1.12.1.js')
                ->appendFile('/js/bootstrap/bootstrap.min.js')
//                           ->prependFile('/js/jQuery-2.1.4.min.js?ver=2')
//               ->prependFile('/js/galeria/jquery.js')
//                           ->appendFile('/js/galeria/jquery.prettyPhoto.js')
//                           ->appendFile('/js/galeria/wowslider.js')
                ->appendFile('/js/bootstrap/assets/ie-emulation-modes-warning.js')	
                ->appendFile('/js/jquery.final-countdown.js')
                ->appendFile('/js/kinetic.js')
                ->appendFile('/js/default.js')
;
		?>
            
<link rel='stylesheet' id='style-css'  href='/scripts/diapo.css' type='text/css' media='all'/>
  <!--<script src="http://maps.google.com/maps/api/js?v=3&amp;sensor=false"></script>-->
<!--<script type='text/javascript' src='/scripts/jquery.min.js'></script>-->
<!--[if !IE]>
<!--[if !IE]><!-->
<!--<script type='text/javascript' src='/scripts/jquery.mobile-1.0rc2.customized.min.js'></script>-->
<!--<![endif]-->
<!--<script type='text/javascript' src='/scripts/jquery.easing.1.3.js'></script>-->
<!--<script type='text/javascript' src='/js/galeria/jquery.js'></script>-->

<script type='text/javascript' src='/scripts/jquery.hoverIntent.minified.js'></script>
<script type='text/javascript' src='/scripts/diapo.js'></script>
            
            
<!--<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>-->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/js/bootstrap/assets/ie8-responsive-file-warning.js"></script><![endif]-->
   <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
     <!-- End slider-->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<link rel="shortcut icon" href="/img/favicon.png" type="image/x-icon"/>
	
</head>
    <body class="homepage">
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<style>
.navbar-inverse .navbar-nav>li>a:focus,.navbar-inverse .navbar-nav>li>a:hover{
/*color:#000!important;*/
background-color:transparent}
.dropdown-menu > li.kopie > a {
    padding-left:5px;
}

.dropdown-submenu {
    position:relative;
}
.dropdown-submenu>.dropdown-menu {
   top:0;left:100%;
   margin-top:-6px;margin-left:-1px;
   -webkit-border-radius:0 6px 6px 6px;-moz-border-radius:0 6px 6px 6px;border-radius:0 6px 6px 6px;
 }

.dropdown-submenu > a:after {
  border-color: transparent transparent transparent #333;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  content: " ";
  display: block;
  float: right;
  height: 0;
  margin-right: -10px;
  margin-top: 5px;
  width: 0;
}

.dropdown-submenu:hover>a:after {
    border-left-color:#555;
 }

.dropdown-menu > li > a:hover, .dropdown-menu > .active > a:hover {
  text-decoration: underline;
}

@media (max-width: 767px) {

  .navbar-nav  {
     display: inline;
  }
  .navbar-default .navbar-brand {
    display: inline;
  }
  .navbar-default .navbar-toggle .icon-bar {
    background-color: #fff;
  }
  .navbar-default .navbar-nav .dropdown-menu > li > a {
    color: red;
    background-color: #ccc;
    border-radius: 4px;
    margin-top: 2px;
  }
   .navbar-default .navbar-nav .open .dropdown-menu > li > a {
     color: #333;
   }
   .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
   .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
     background-color: #ccc;
   }

   .navbar-nav .open .dropdown-menu {
     border-bottom: 1px solid white;
     border-radius: 0;
   }
  .dropdown-menu {
      padding-left: 10px;
  }
  .dropdown-menu .dropdown-menu {
      padding-left: 20px;
   }
   .dropdown-menu .dropdown-menu .dropdown-menu {
      padding-left: 30px;
   }
   li.dropdown.open {
    border: 0px solid red;
   }

}

@media (min-width: 768px) {
  ul.nav li:hover > ul.dropdown-menu {
    display: block;
  }
  #navbar {
    text-align: center;
  }
}

		.affix {
			top: 0;
			width: 100%;
		}

		.affix + .container-fluid {
			padding-top: 100px;
		}

		</style>
<div>
    <div class="div_cabecera1 ">   
  <?php echo $this->partial('/layout/menu.phtml',array('idioma'=>$this->idioma ));?>
</div>
    </div>

    <!-- ====================================================================================================== -->
<div class="container-fluid" style="">
    <div class="container" style="padding: 0px;">
    <?php echo $this->layout()->content;?>
    </div>
</div>

<div class="bajar"></div>
<!-- PIE -->
<!--<div class="container-fluid">-->
<div  id="pie" class="container">
<!--<div class="col-md-6">  </div>
<div class="col-md-6"></div>-->
<!--<div class="bajar"></div>-->
<!--<p class="copyright">© Copyright 2016 Codesur Cochabamba 2018</p>-->
</div>
<div class="col-md-12 " style="padding: 0px;">
<div class="menu_head">
        <nav class="navbar navbar-inverse   " role="navigation" style="margin-bottom: 0px; border: none;"><!--navbar-fixed-top-->
        <div class="container ">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
             
            </div>
            <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav  ">
                    <li>  <a href="<?php echo $this->url(array('idioma'=>$this->idioma),'inicio')?>">COCHA 2018</a>                    </li>
                    <li>   <a href="<?php echo $this->url(array('idioma'=>$this->idioma),'voluntariado_'.$this->idioma)?>"><?php echo $this->translate("VOLUNTARIADOS")?></a>                  </li>
                   <li>    <a href="<?php echo $this->url(array('idioma'=>$this->idioma),'contacto_'.$this->idioma)?>"><?php echo $this->translate("CONTACTANOS")?></a>                 </li>
                   <li> </li>
                </ul>
                <p class="copyright" style=" padding-top: 12px;">© Copyright 2016 Codesur Cochabamba 2018</p>
            </div>
        </div>
    </nav>    
  </div>
</div>
<!--</div> fin pie -->
<!--</div> fin contenedor -->
<script src="/js/bootstrap/assets/ie10-viewport-bug-workaround.js"></script>
<script language="JavaScript">
//var escroll = jQuery.noConflict();
//escroll(window).scroll(function(){
//    if (window.pageYOffset >= 190) {
////        $('#div').css("position","fixed");
//escroll("#nav_men_he").attr('class', 'col-md-12');
//    }else{
//      escroll("#nav_men_he").attr('class', 'col-md-12');  
//    }
//});
// alert (screen.width);

//document.writeln(screen.width + " x " + screen.height) ;
</script>
</script> 
</body>

</html>

