<html>
<head>		
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<style type="text/css" media="print">
body
{
		margin:0;
		padding:0;				
		margin: 3em;
}

				

	
</style>
</head>
<body onload="javascript:print();close();">
<table style="margin: 2%">
<tr>
<td>
<h2 style="margin-bottom: 0;text-align: center;"><?php echo NOMBRE_SITIO;?></h2>
<h4 style="margin-top: 0;margin-bottom: 5px;text-align:center"><?php echo LEMA_SITIO;?></h4>
</td>
</tr>

<?php if($this->titulo){
echo "<tr>";
echo "<td>";
	echo "<h1>".$this->titulo."</h1>";
echo "</td>";
echo "</tr>";
 }?>


<?php if($this->contenido1){
echo "<tr>";
echo "<td>";
 	echo $this->contenido1;
echo "</td>";
echo "</tr>";
 }?>
 
 <?php if($this->contenido2){
echo "<tr>";
echo "<td>";
 	echo $this->contenido2;
echo "</td>";
echo "</tr>";
 }?>
 
 <?php if($this->contenido3){
echo "<tr>";
echo "<td>";
 	echo $this->contenido3;
echo "</td>";
echo "</tr>";
 }?>
 
 <?php if($this->contenido4){
echo "<tr>";
echo "<td>";
 	echo $this->contenido4;
echo "</td>";
echo "</tr>";
 }?>
 
 <?php if($this->contenido5){
echo "<tr>";
echo "<td>";
 	echo $this->contenido5;
echo "</td>";
echo "</tr>";
 }?>
 </table>
</body>
</html>
