  
<?php if($this->principal){
    ?>
<div id="callout-helper-context-color-specificity" class="bs-callout bs-callout-info">
            <h3><?php echo $this->translate("Listado de Noticias")?>        
	    </h3>
        </div>
<?php 
          $dat=$this->principal;
          foreach ($dat as $d){
              $enlace=$this->url(array('idioma'=>$this->idioma,'alias_noticia'=>$d['not_alias_'.$this->idioma]),'noticia_completa_'.$this->idioma);
          ?>
      <div class="caja_noticia">
          <div class="caja_img col-md-4 thumbnail">
              <img src="/upload/noticia/thumb/s<?php echo $d["not_img"]?>" title="<?php echo $d["not_titulo_".$this->idioma]?>" style="border-radius:14px;" />
          </div>
          <div class="col-md-8 caja_decripcion">
          <h3>
              <a href="<?php echo $enlace?>"><?php echo $d["not_titulo_".$this->idioma]?></a></h3>
              <p style="text-align: justify;"><?php echo Util_Cortartexto::cortar_texto($d["not_cuerpo_".$this->idioma], 300);?></p> 
          </div>
          
      </div>
          <?php } }else{     ?>
      <h3>
          <?php echo $this->translate("No se tiene informacion")?></h3>
      <?php }?>
 <div class="bajar"></div>
<div id="not_paginacion">
   <div class="paginador_g3">	<?php	echo $this->paginationControl($this->principal,'Sliding',	'paginar_g2.phtml');?>	</div>  
</div>
