<div id="callout-helper-context-color-specificity" class="bs-callout bs-callout-info">
    <h3><?php echo $this->translate("HISTORIA")?> <?php echo $this->noticia["his_titulo_".$this->idioma];?></h3>
    <p><span><?php //echo $this->noticia["his_titulo_original_".$this->idioma];?></p>
  </div>
<div class=" col-md-12">
    <div class="col-md-8 " style="text-align: center;margin-bottom: 17px;">
        <img src="/upload/historia/<?php echo $this->noticia["his_img1"]?>" title="<?php echo $this->noticia["his_titulo_".$this->idioma]?>" class=" img-rounded" />
    </div>
    <p class="text-muted" style="text-align: justify;"><?php echo $this->noticia["his_descripcion_".$this->idioma];?></p>
</div>
<div class="bajar"></div>
<div style="color: #000;"><?php echo $this->translate("Fuente_Bibliografica")?>: <?php echo $this->noticia["his_referencia"]?></div>
<div class="bajar"></div>
<div id="callout-helper-context-color-specificity" class="bs-callout bs-callout-info">
    <h3><?php echo $this->noticia["his_titulo_img_".$this->idioma];?></h3>
</div>
<div class=" col-md-12" style="text-align: center;">
   <img src="/upload/historia/<?php echo $this->noticia["his_img2"]?>" title="<?php echo $this->noticia["his_titulo_img_".$this->idioma]?>" class=" img-rounded" />
    
</div>