<?php 
echo $this->partial("layoutizquierda/boton.phtml",array('pais'=>$this->pais,'ciudad'=>$this->ciudad));
echo $this->partial("layoutizquierda/ciudades.phtml",array('pais'=>$this->pais,'ciudad'=>$this->ciudad));
//echo $this->partial("layoutizquierda/banner.phtml",array('pais'=>$this->pais));
echo $this->partial("layoutizquierda/publicidad.phtml",array('pais'=>$this->pais,'pos_banner'=>$this->pos_banner));

?>


