<div class="row" style="margin: 8px 0px 0px 0px;">
    <div class="col-md-8" style=" border: 1px solid #cdcdcd;    padding: 3px 0 5px;">
        <h2 style="  font-size: 28px;    margin: 0 0 6px;    text-align: center;    text-decoration: -moz-anchor-decoration;    ">
        <?php echo $this->pdf["pdf_titulo_".$this->idioma];?></h2>
    <iframe src="/upload/galeria_fotos/<?php echo $this->pdf["pdf_documento"]?>" style="width:100%; height:800px;" frameborder="0"></iframe>
    
</div>
    <div class="col-md-4" style="padding: 0px;">
           <?php echo $this->partial('/layout/cronometro.phtml',array('idioma'=>$this->idioma )); ?> 
     
     </div>
    <div class="col-md-4" style="padding: 0px; text-align:  center;">
           <?php echo $this->partial('/layout/facebook.phtml',array('idioma'=>$this->idioma )); ?> 
     
     </div>
</div>